name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        nim: ['devel', 'version-1-4']
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: jason

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Run tests
        shell: bash
        run: |
          cd jason
          nimble --accept develop
          nimble test

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        shell: bash
        run: |
          cd jason
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --path="." --outdir:docs \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            jason.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.os == 'ubuntu-latest' && matrix.nim == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: jason/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
